module.exports = {
    NULL_VALUE: "No value required",
    OUT_OF_VALUE: "Parameter value is incorrect",
    ALREADY_ID: "Id already exists",
    NO_LOUNGE: "The lounge id does not exist",
    LOUNGE_READ_ALL_SUCCESS: "Success to query all lounge lists",
    LOUNGE_READ_ALL_FAIL: "Fail to query all lounge lists",
    LOUNGE_CREATE_SUCCESS: "Success to create lounge info",
    LOUNGE_CREATE_FAIL: "Fail to create lounge info",
    LOUNGE_UPDATE_SUCCESS: "Success to update lounge info",
    LOUNGE_UPDATE_FAIL: "Fail to update lounge info",
    LOUNGE_DELETE_SUCCESS: "Success to delete lounge info",
    LOUNGE_DELETE_FAIL: "Fail to delete lounge info",
    BADGE_READ_ALL_SUCCESS: "Success to query all badge lists",
    BADGE_READ_ALL_FAIL: "Fail to query all badge lists",
    BADGE_CREATE_SUCCESS: "Success to create badge info",
    BADGE_CREATE_FAIL: "Fail to create badge info",
    BADGE_UPDATE_SUCCESS: "Success to update badge info",
    BADGE_UPDATE_FAIL: "Fail to update badge info",
    BADGE_DELETE_SUCCESS: "Success to delete badge info",
    BADGE_DELETE_FAIL: "Fail to delete badge info",
    NO_BADGE: "The badge id does not exist",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
   
}